services:
  mc-status-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOPROXY: "${GOPROXY:-https://goproxy.cn|https://goproxy.io|https://proxy.golang.org|direct}"
    image: mc-status-go:latest
    container_name: mc-status-go
    restart: unless-stopped
    environment:
      - icon=false
    ports:
      - "8080:8080"
    command: ["-listen", ":8080", "-timeout", "5s"]
